power_estimation/urls.py
from django.urls import path
from . import views

app_name = 'power_estimation'

urlpatterns = [
    path('', views.index, name='index'),
    path('test2/', views.test2, name='test2'),
    path('charts/', views.chartsview, name='charts'),
    path('tables/', views.tablesview, name='tables'),
    path('user/', views.userview, name='user'),
    path('user2/', views.userview2, name='user2'),
    path('expert/', views.expertview, name='expert'),
    path('select/', views.selected, name='selected'),
    path('filepath/', views.filepath, name='filepath'),
    path('filepath2/', views.filepath2, name='filepath2'),
    #path('mychart/', views.chartview, name='mychart'),
]

power_project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('power_estimation/', include('power_estimation.urls')),
    path('admin/', admin.site.urls),
]

power_estimation/models.py
from statistics import mode
from django.db import models

# Create your models here.
class test_table(models.Model):
    name = models.CharField(max_length=50)
    introduction = models.TextField()
    area = models.CharField(max_length=50)
    party_number = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name

class parameter(models.Model):
    icc1 = models.FloatField(max_length=10)
    icc2 = models.FloatField(max_length=10)
    name = models.CharField(max_length=10)
    sample = models.CharField(max_length=10)
    Field5 = models.FloatField(max_length=10)
    
    def __str__(self):
        return self.name

class ctrl(models.Model):
    name = models.CharField(max_length=10)
    ud = models.FloatField(max_length=10)
    nd = models.FloatField(max_length=10)
    phyh = models.FloatField(max_length=10)
    phyl = models.FloatField(max_length=10)

    def __str__(self):
        return self.name

power_estimation/views.py
from multiprocessing import context
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.db.models import Sum

from .models import test_table, parameter, ctrl
from .calculation import *
import json
# Create your views here.


def index(request):    
    return render(request, 'power_estimation/test.html')

### 클릭 --> 데이터 열어서 출력하기 (done)
### sqlite에 있는 데이터 db(모델)로 연결 (같은건가?) --> sqlite에 id column 필요! (done)
### input으로 nand 이름 받아서(드롭다운메뉴?) (done: input type=submit 추가) // 
### 계산 후 (다른 파일로 가서 계산해서 sql로 넣어야 할듯. done(calcultion_test)) // 결과 출력해보기 (표 형태 --> 가능하면 차트도?)
### html 구성해보기
### CTRL별로 세부 파일 리스트 만들기
### ELAN 누르면 세부 elan 데이터들 불러오기
### 세부 데이터 누르면 밑에 테이블에 반영 ㄱㄱ

def test2(request):
#     month_text = request.GET.get('month')

#     if month_text == '01':

#         calculation_test()
        
#         candidates = parameter.objects.all()
#         # candidates = parameter.objects.filter(name='nvcc')[0]
#         context = {'candidates':candidates}

#         return render(request, 'power_estimation/test2.html', context)

    return render(request, 'power_estimation/test2.html')

def chartsview(request):
    return render(request, 'power_estimation/charts.html')

def tablesview(request):
    return render(request, 'power_estimation/tables.html')

def userview(request):
    return render(request, 'power_estimation/usermode.html')

def userview2(request):
    return render(request, 'power_estimation/usermode2.html')    

def expertview(request):
    return render(request, 'power_estimation/expertmode.html')

def selected(request):
    ctrl_sel = request.GET.get('CTRL를 골라보자 !') ### value를 가져오는 듯. value를 파일 이름으로 해서 불러오게 하기 가능?

#    update_ctrl(ctrl_sel)

    candidates = ctrl.objects.filter(name=ctrl_sel) ### 한개만 골라서 보내기! 지금 받은 선택지의 value
    # candidates = ctrl.objects.values('name').annotate(ud_sum=Sum('ud'))
    context = {'candidates':candidates} ### 여러개 딕셔너리로 전달하면 골라서 출력할 수 있을 듯

    return render(request, 'power_estimation/usermode.html', context)

    # return HttpResponseRedirect(reverse('power_estimation:userview'))

def filepath(request):
    name = []
    queryset = ctrl.objects.all()
    for item in queryset:
        name.append(item.name)

    return JsonResponse(data={
        'name': name, ###[ctrl_1, ctrl_2] 각각이 data.item
    })

def filepath2(request):

    ctrl_sel = request.GET.get('name')
    
    name = [ctrl_sel]
    # queryset = ctrl.objects.filter(name=ctrl_sel)
    # for item in queryset:
    #     name.append(item.name)

    return JsonResponse(data={
        'name': name, ###[ctrl_1, ctrl_2] 각각이 data.item
    })

        # candidates = ctrl.objects.values(ctrl_sel).annotate(ud_sum=Sum('ud'))
        # context = {'candidates':candidates}

        # return render(request, 'power_estimation/usermode2.html', context)


# def chartview(request): ######################################   ajax 연습용
#     # ctrl_sel = request.GET.get('CTRL를 골라보자 !')

#     labels = []
#     data = []

#     #queryset = ctrl.objects.filter(name='ctrl_1').values('name').annotate(ud=Sum('ud'))
#     queryset = ctrl.objects.all()
#     for entry in queryset:
#         labels.append(entry.name)
#         data.append(entry.nd)
    
#     return JsonResponse(data={
#         'labels': labels,
#         'data': data,
#     })

#     # candidates_chart = ctrl.objects.filter('ctrl_1') ### 한개만 골라서 보내기! 지금 받은 선택지의 value
#     # # candidates = ctrl.objects.values('name').annotate(ud_sum=Sum('ud'))
#     # context = {'candidates_chart':candidates_chart}

#     # return render(request, 'power_estimation/usermode.html', context)

power_estimation/templates/power_estimation/test.html
<!DOCTYPE html>

{% load static %}
<html lang="en">


<head>
    <meta charset="UTF-8">
    <title>Welcome to Power Estimation Party ! ! !</title>
    <style>
        #header {
            background-color:lightgrey;
            height:100px;
        }
        #nav {
            background-color:#339999;
            color:white;
            width:200px;
            height:1000px;
            float:left;
        }
        #section {
            width:2000px;
            text-align:center;
            float:left;
            padding:10px;
            
        }
        #footer {
            background-color:#FFCC00;
            height:100px;
            clear:both;
        }
        #header, #nav, #section, #footer { text-align:center; }
        #header, #footer { line-height:100px; }
        #nav, #section { line-height:50px; }
        
        /* table border for whole table*/
        .table-bordered {
            border: 1px solid #e3e6f0;
        }
        
        /* table border for each cell*/
        .table-bordered th,
        .table-bordered td {
            padding: 0.75rem;
            vertical-align: top;
            border: 1px solid #e3e6f0;
        }

        /* table border bottom line for head cells*/
        .table-bordered thead th,
        .table-bordered thead td {
            border-bottom-width: 2px;
        }


    </style>
    <!-- Custom styles for this template-->
    <!-- <link href="{% static 'power_estimation/test.css' %}" rel="stylesheet">
    <link href="{% static 'power_estimation/style.css' %}" rel="stylesheet"> -->
    
</head>


<body>

    <h1>Let's Go, Power Estimation !</h1>
	<div id="header">
		<h2>Welcome to Power Estimation Party ! ! !</h2>
	</div>
	<div id="nav">
		<li class="nav-item active">
            <a class="nav-link" href="{% url 'power_estimation:index' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <h2>Home</h2></a>
        </li>

        <!-- Nav Item - Charts -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'power_estimation:test2' %}">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Test Mode</span></a>
        </li>

        <!-- Nav Item - Charts -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'power_estimation:user' %}">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>User Mode</span></a>
        </li>

        <!-- Nav Item - Charts -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'power_estimation:user2' %}">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>User Mode2</span></a>
        </li>

        <!-- Nav Item - Tables -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'power_estimation:expert' %}">
                <i class="fas fa-fw fa-table"></i>
                <span>Expert Mode</span></a>
        </li>

	</div>
	<div id="section">
		<p>index page</p>

        
	</div>
	<div id="footer">
		<h2>FOOTER 영역</h2>
	</div>

</body>

    

</html>

power_estimation/templates/power_estimation/test2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>해바라기반 반장선거</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>icc1</B></td>
            <td><B>icc2</B></td>
            <td><B>name</B></td>
            <td><B>아무말1</B></td>
            <td><B>아무말2</B></td>
        </tr>
        </thead>
        <!-- <tbody>
        {% for candidate in candidates %}
        <tr>
            <td>{{candidate.icc1}} A</td>
            <td>{{candidate.icc2}} mA</td>
            <td>{{candidate.name}}</td>
            <td>{{candidate.sample}}</td>
            <td>{{candidate.Field5}}</td>
        </tr>
        {% endfor %}
        <tbody> -->
    </table>
</body>